### ISSUE TITLE
Search bar not aligned

### ISSUE THREAD

**Issue by Exar04** [GDSC-PHCET/todo-list#11]
<img width="532" alt="Screenshot 2023-10-12 at 7 12 14 PM" src="https://github.com/GDSC-PHCET/todo-list/assets/109629956/4aaf8f6f-8696-4024-8026-6e2b95111534">

**Comment by Vibranium1** [comment]
there is no search bar, you can assign this to me

**Comment by Exar04** [comment]
Um i meant AddTaskBar.
Altho can you explain what do you mean by adding search bar?
Do you mean to add search bar to search the ToDo's added?

**Comment by Exar04** [comment]
@Vibranium1 Create an new issue explaining the search bar thing you mentioned. I am closing this issue as it is solved

**Comment by Vibranium1** [comment]
I was telling about the search bar which could be used to search from the ToDo's added.
