### ISSUE TITLE
align main container correctly

### ISSUE THREAD

**Issue by vishwas-babar** [GDSC-PHCET/todo-list#14]
add some top margin to top of main container.

**Comment by vishwas-babar** [comment]
solved issue #14.

added top margin to main container - 

![image](https://github.com/GDSC-PHCET/todo-list/assets/116264015/bb3c63bf-6ae4-460b-a971-014befff7af8)

pushed this changes to version2 branch

**Comment by Exar04** [comment]
Thanks for contributing but just mention the issue id in pr next time.
