### ISSUE TITLE
Add Dark mode Logo and align it in the right corner

### ISSUE THREAD

**Issue by Exar04** [GDSC-PHCET/todo-list#20]
<img width="1440" alt="Screenshot 2023-10-18 at 9 30 47 PM" src="https://github.com/GDSC-PHCET/todo-list/assets/109629956/0d28022c-c0bf-42ac-ae29-4951919ad173">
Right now we can switch between dark mode and light mode using this toggle. But it is in between tasks and its kinda annoying.
It would be great it we align that dark mode toggle in the top right corner and add logo instead of text and toggle

**Comment by Exar04** [comment]
@Vibranium1 Would you like to work on this?

**Comment by Vibranium1** [comment]
Sure, you can assign me

**Comment by Vibranium1** [comment]
Can you please add "hactoberfest" and "hactoberfest-accepted" tags , it will really help !!

**Comment by vishwas-babar** [comment]
please if issues are solved then close it

**Comment by Vibranium1** [comment]
Hey @Exar04 , I have submitted my PR, can you look onto it.

**Comment by Exar04** [comment]
sry for the late review n thanks. That UI looks lit now mate.
