### ISSUE TITLE
Add dark mode 

### ISSUE THREAD

**Issue by Exar04** [GDSC-PHCET/todo-list#8]

**Comment by Vibranium1** [comment]
you can assign this to me.

**Comment by smartboys790** [comment]
i am working on it....

**Comment by Exar04** [comment]
@smartboys790 you had created clone folder inside the repo thats why i had to revert your commit. Make those changes in original files only and make a fresh pr.
Also mention issue id in pr

**Comment by Vibranium1** [comment]
@Exar04 Hey I have submitted by PR, can you look onto it.

**Comment by Exar04** [comment]
Thanks for your contribution @Vibranium1
